#!/usr/bin/env ruby

require 'chunky_png'

class File
  def read_until_byte(byte, max: nil, keep: false)
    last = nil
    buf = ''
    
    count = 0
    while not eof? and (not max or count < max) and (not last or last.bytes.first != byte)
      count +=1 
      buf << last if last
      last = read 1
    end
    
    ungetc last if keep
    
    buf
  end
end


class Graphic
  def write_graphic(graphic, title)
    filename = "out/#{title}.png"
  
    bytes = graphic[:bytes]
    width = graphic[:width]
    raw_width = graphic[:raw_width] || width
    height = graphic[:height] || bytes.length * 8 / width
    scale_x = graphic[:scale_x] || 4
    scale_y = graphic[:scale_y] || 4
    
    puts "Saving #{filename} [#{width}x#{height}] x (#{scale_x}, #{scale_y})"
  
    png = ChunkyPNG::Image.new(width * scale_x, height * scale_y, ChunkyPNG::Color::TRANSPARENT)
    bytes.unpack("B*").first.chars.each_slice(raw_width).each_with_index do |row, y|
      row.each_with_index do |bit, x|
        color = ChunkyPNG::Color(bit == "1" ? 'black' : 'white')
        (0...scale_y).each do |i|
          (0...scale_x).each do |j|
            begin
              png[x * scale_x + j, y * scale_y + i] = color
            rescue
            end
          end
        end
      end
    end
  
    png.save filename
  end
end

class PMPlus < Graphic
  def import(filename)
    file = open filename
    index = 0
  
    titles = read_titles filename
    gra = filename.downcase =~ /\.gra$/
  
    until file.eof? or (gra and index >= 1) do
      puts "*** #{titles[index]} ***"
      #graphic = read_graphic file
      graphic = read_graphic_gra file
      write_graphic graphic, titles[index]
      index += 1
    end
  end

  def read_titles(filename)
    return [filename.split('/').last.split('.').first] if filename.downcase =~ /\.gra$/
    
    sdr = open filename.sub('.SHP', '.SDR')
    sdr.each_char.each_slice(16).map do |x|
      nul = false
      str = ''
      i = 0
      while !nul
        char = x[i]
        i += 1
        if char == "\0"
          nul = true
        else
          str = str + char
        end
      end
      #x.join().sub(/\0+/, '').strip
      str.strip
    end
  end

  def read_graphic(shp)
    header_size = 4
    width_bytes, height, width, zero = shp.read(header_size).unpack('C*')
    byte_count = width_bytes * height
    bytes = shp.read(byte_count)
    #bytes.unpack("B*").first.chars.each_slice(width) { |x| puts x.join('') }
    puts "read_graphic width_bytes #{width_bytes} | height #{height} | width #{width} | zero #{zero}"
  
    extra_byte = shp.read(1).unpack('C') # Should be 115?
  
    { bytes: bytes, width: width, height: height, raw_width: width_bytes * 8, scale_x: 4, scale_y: 7 }
  end
  
  def read_graphic_gra(gra)
    _1, _2, width, zero, height, _3, _4, _5 = gra.read(8).unpack('C*')
    width_bytes = width / 8
    byte_count = width_bytes * height
    puts "read_graphic width_bytes #{width_bytes} | height #{height} | width #{width} | zero #{zero} | byte_count #{byte_count}"
    
    
    bytes = ""
    rec_size = 12
    
    until gra.eof?
      line = gra.read rec_size
      bytes += line[0...(rec_size-1)]
    end
    
    { bytes: bytes, width: width, height: height, raw_width: width_bytes * 8, scale_x: 4, scale_y: 7 }
  end
end

class PrintShop < Graphic
  def import(file)
    dat = open file
    index = 0
  
    titles = read_titles file
  
    until dat.eof? do
      puts "*** #{titles[index]} ***"
      graphic = read_graphic dat
      write_graphic graphic, titles[index]
      index += 1
    end
  end

  def read_titles(file)
    sdr = open file.sub('.DAT', '.NAM')
    sdr.each_char.each_slice(16).map { |x| x.join().strip }
  end

  def read_graphic(dat)
    width = 88
    width_bytes = 11
    height = 52
    byte_count = width_bytes * height
    bytes = dat.read(byte_count)
    bytes.unpack("B*").first.chars.each_slice(width) { |x| puts x.join('') }
  
    { bytes: bytes, width: width, height: height }
  end
end

class NewPS < Graphic
  def import(file)
    shp = open file
    index = 0
  
    titles = read_titles file
    
    header_size = 10
    file_header = shp.read header_size
  
    until shp.eof? or !titles[index] do
      puts "*** #{titles[index]} ***"
      graphic = read_graphic shp
      write_graphic graphic, titles[index]
      index += 1
    end
  end

  def read_titles(file)
    sdr = open file.sub('.PNG', '.PNM')
    sdr.each_char.each_slice(16).map { |x| x.join().strip }
  end

  def read_graphic(shp)
    #header_size = 10
    #header = shp.read(header_size)
    #width_bytes, height, width, zero = shp.read(header_size).unpack('C*')
    width = 88
    width_bytes = 11
    height = 52
    
    byte_count = width_bytes * height
    bytes = shp.read(byte_count)
    bytes.unpack("B*").first.chars.each_slice(width) { |x| puts x.join('') }
  
    #extra_byte = shp.read(1).unpack('C') # Should be 115?
  
    { bytes: bytes, width: width, height: height }
  end
end

class PrintMagic < Graphic
  def import(filename)
    file = open filename
    index = 0
  
    title = filename.split('/').last.split('.').first
    
    header_size = 24
    file_header = file.read header_size
    
    width = file_header[10..11].unpack('S<').first
    raw_width = width + (8 - width % 8)
    
    bytes = read_graphic file
    write_graphic({bytes: bytes, width: width, raw_width: raw_width}, title)
  end
  
  def read_graphic(file)
    bytes = []
  
    pos = 0
    until file.eof?
      byte = file.read(1)
      if byte.unpack('C').first == 0xBF
        run = file.read(1).unpack('C').first + 1
        char = file.read(1)
        bytes << char * run
      else
        bytes << byte
      end
    end
    
    bytes.join
  end
end

class PrintPower < Graphic
  def import(filename)
    path = filename.split('/')[0..-2].join('/')
    graphics = read_index filename
    puts graphics.inspect

    filename = "#{path}/GV11.001"
    file = open filename
    file_header = file.read 4
    while not file.eof?
      read_graphic file
    end
    #write_graphic({bytes: bytes, width: width, raw_width: raw_width}, title)
  end
  
  def read_graphic(file)
    $graphic ||= 0
    $graphic += 1
    
    puts "****** READING GRAPHIC #{$graphic} AT OFFSET #{file.pos} 0x#{file.pos.to_s(16)}"
    h = file.read(9)
    file.ungetc(h)
    puts "HEADER #{h.unpack('C*')} #{h.unpack('S')}"
    
    start_pos = file.pos
    length = file.read(2).unpack('S').first
    header = file.read(6).unpack('C*')
    run_char = file.read(1).unpack('C').first
    
    if $graphic == 2
      length = 818
    elsif $graphic == 3
      #length = 1458
      #length = 1462
      #length = 1465
      #length = 1479
      #length = 1479
      #length = 1482
      length = 1490
    elsif $graphic == 4
      length = 1000
    end
    
    puts "run_char #{run_char} length #{length} header #{header.inspect}"

    @bitmap = Hash.new { |h,k| h[k] = [] }
    
    @row = 0
    @col = 0
    last_char = ''
    char = file.read 1
    done = false
    
    while !done and char and file.pos < (start_pos + length)
    #while char and (char != '\xFF' and last_char != '\xFF')
      puts "[#{char.inspect}]" if file.pos == start_pos
      
      byte = char.unpack('C').first
      if byte == run_char #0x0a # or byte == 0x0a #byte < 0x10
        char = file.read(1) rescue ''
        run = file.read(1).unpack('C').first rescue 0
        done = true if run == 0
        
        run.times do |i|
          write_byte_to_bitmap char
        end
      else
        write_byte_to_bitmap char
      end
      
      char = file.read 1
    end

    print_bitmap
  end
  
  def write_byte_to_bitmap(char)
    rows = 112
    byte = char.unpack('C').first
    
    (0..7).each do |i|
      @bitmap[@row][@col + (7-i)] = (byte & 2**i) > 0
    end
    
    @row = @row + 1
    if @row >= rows
      @row = 0
      @col = @col + 8
    end
  end
  
  def print_bitmap
    row = 0
    col = 0
    
    (0..@bitmap.keys.max).each do |row|
      puts (@bitmap[row] || []).map { |val| val ? 'X' : ' '}.join
    end
  end
  
  def read_index(filename)
    file = open filename
    title = file.read_until_byte 155
    graphics = []
    while not file.eof?
      rec = file.read_until_byte 155
      graphics << [rec.split('\\').first, rec]
    end
    
    graphics
  end
end

def import(file)
  if file.downcase =~ /\.shp/
    PMPlus.new.import file
  elsif file.downcase =~ /\.dat/
    PrintShop.new.import file
  elsif file.downcase =~ /\.png/
    NewPS.new.import file
  elsif file.downcase =~ /\.pmg/
    PrintMagic.new.import file
  elsif file.downcase =~ /\.gra/
    PMPlus.new.import file
  elsif file.downcase =~ /graphics.\d\d\d$/
    PrintPower.new.import file
  end
end

ARGV.each { |f| import f }
